#composer install --ignore-platform-reqs --working-dir=/app/akademik-agoy.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/api-admin-rumah-kevin.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/api-antrian-guse.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/api-pendataan-afandi.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/api-pendataan-ranya.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/e-canteen-fadilatul.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/e-learning-rindi.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/forum-diskusi-maruli.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/forum-diskusi-maruli.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/inventaris-fathiyah.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/panti-fadilatul.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/pendaftaran-pasien-andri.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/penjualan-kue-zaky.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/penjualan-tanah-andini.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/perpustakaan-andri.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/perpustakaan-febilina.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/perpustakaan-febriadi.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/perpustakaan-hendra.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/perpustakaan-roza.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/persediaan-desy.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/riwayat-kunjungan-pasien-rivaldy.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/sistem-informasi-sekolah-riza.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/spk-perumahan-david.bikinaplikasi.dev
##composer install --ignore-platform-reqs --working-dir=/app/toko-kelontong-maria.bikinaplikasi.dev

#/composer install --ignore-platform-reqs --working-dir=/app/klinik-nando.bikinaplikasi.dev#
#/composer install --ignore-platform-reqs --working-dir=/app/klinik-akbar.bikinaplikasi.dev#
#/composer install --ignore-platform-reqs --working-dir=/app/klinik-ardana.bikinaplikasi.dev#
#composer install --ignore-platform-reqs --working-dir=/app/reservasi-dan-travel-zaky.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/kepegawaian-ziqin.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/kepegawaian-ziqin.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spk-blt-covid-muhammad-ridho.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/reservasi-dan-travel-skytravelink.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/pemesanan-kos-kosan-galuh.bikinaplikasi.dev
#composer update --ignore-platform-reqs --working-dir=/app/pemesanan-kos-kosan-galuh.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spk-profile-matching-nurina.bikinaplikasi.dev
#composer update --ignore-platform-reqs --working-dir=/app/spk-profile-matching-nurina.bikinaplikasi.dev
#
#composer install --ignore-platform-reqs --working-dir=/app/spp-sekolah-nisa.bikinaplikasi.dev
#composer update --ignore-platform-reqs --working-dir=/app/spp-sekolah-nisa.bikinaplikasi.dev
#
#composer install --ignore-platform-reqs --working-dir=/app/persediaan-sj.bikinaplikasi.dev
#composer update --ignore-platform-reqs --working-dir=/app/persediaan-sj.bikinaplikasi.dev

#composer install --ignore-platform-reqs --working-dir=/app/pemesanan-cafe-ardana.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/pengarsipan-surat-fikri.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/pemesanan-advertising-alfatah.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spk-transportasi-annisa.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spk-guru-teladan-anggi.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/pengiriman-paket-yandi.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/penjualan-perlengkapan-bayi-putri.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spk-profile-matching-nurina.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spp-sekolah-nisa.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/api-admin-faithaction-api.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/bimble-bayu.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/spk-ahp-beasiswa-as.bikinaplikasi.dev
#composer install --ignore-platform-reqs --working-dir=/app/gis-pemancingan-rezil.bikinaplikasi.dev
# composer install --ignore-platform-reqs --working-dir=/app/api-admin-reaperscans-aldi.bikinaplikasi.dev
# composer install --ignore-platform-reqs --working-dir=/app/pemesanan-badminton-rajum.bikinaplikasi.dev
# composer install --ignore-platform-reqs --working-dir=/app/spk-roc-makanan-aldi.bikinaplikasi.dev