<?php

namespace App\Http\Controllers;

use File;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Http;
use phpseclib3\Net\SSH2;

class BotTradingController extends Controller
{

    // public $margin = 79.32;
    // public $marginToAddPosition = 79.32;
    // public $leverage = 10;
    // public $takeProfit = 60;
    // public $stopLoss = 15;
    // public $takeProfiteOnAddPosition = 20;
    // public $stopLossOnAddPosition = 20;
    // public $koinId = 22;
    public $isLive = true;

    public $margin = 79.32;
    public $marginToAddPosition = 79.32;
    public $leverage = 10;
    public $takeProfit = 60;
    public $stopLoss = 15;
    public $takeProfiteOnAddPosition = 20;
    public $stopLossOnAddPosition = 20;
    public $koinId = 22;
    public $koinName = 'SAND';

    public $token = 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';

    public $apiKey = 'Ej0cJWHTZRPq8iWuBAE7RHPlsuZ3S0FDuZhfga1eFKRvOWOSkzWdsKmTEj8pOcdA3yG3yYd4r3vBx72kBg';
    public $secretKey = 'b8ZCj4JZSnc59LYx99ZbHRgmtOGv9mwDqEB6yCDKLVnTHTfOFXiELKCxN4S0Fp8SORbUjQRTKmy3CcnotKKA';

    public $signature = '612874a78cd496b520b8e99c502035c7c3ab62eaad8f2980cb6d2f2dd1bc6cb6';


    // curl -H 'X-BX-APIKEY: Ej0cJWHTZRPq8iWuBAE7RHPlsuZ3S0FDuZhfga1eFKRvOWOSkzWdsKmTEj8pOcdA3yG3yYd4r3vBx72kBg' -X POST 'https://open-api.bingx.com/openApi/contract/v1/allPosition' -d 'x=x&signature=612874a78cd496b520b8e99c502035c7c3ab62eaad8f2980cb6d2f2dd1bc6cb6'

    public $listOfPriceAlerts = [
        [
            'order_no' => '1141737065340887045',
            'price' => '0.730585',
            'type' => 'Sell',
        ],
    ];

    public function alerts()
    {

        $parameters = [
            'timestamp' => floor(microtime(true) * 1000)
        ];

        $parameters = http_build_query($parameters);

        $signature = explode("= ", exec("echo -n \"$parameters\" | openssl dgst -sha256 -hmac \"$this->secretKey\" -hex"))[1];

        $queryString = $parameters . '&signature=' . $signature;

        $url = 'https://open-api.bingx.com/openApi/contract/v1/allPosition?' . $queryString;
        

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        $headers = array();
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0';
        $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8';
        $headers[] = 'Accept-Language: en-US,en;q=0.5';
        $headers[] = 'Alt-Used: open-api.bingx.com';
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Upgrade-Insecure-Requests: 1';
        $headers[] = 'Sec-Fetch-Dest: document';
        $headers[] = 'Sec-Fetch-Mode: navigate';
        $headers[] = 'Sec-Fetch-Site: none';
        $headers[] = 'Sec-Fetch-User: ?1';
        $headers[] = 'Te: trailers';
        $headers[] = 'X-Bx-Apikey: ' . $this->apiKey;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            dd('Error:' . curl_error($ch));
        }
        curl_close($ch);



        $listOfContracts = $result;
        foreach (json_decode($listOfContracts, true)['data'] as $key => $priceAlert) {
            $file_name_to_check_set_bep = 'has_create_alerts_set_bep_' . $priceAlert['time'];
            $file_name_to_check_add_position = 'has_create_alerts_add_position_' . $priceAlert['time'];
            
            // untuk set bep buy
            if ($priceAlert['positionSide'] == 'LONG' && $priceAlert['currentPrice'] >= $priceAlert['entryPrice'] * 1.019 && !file_exists($file_name_to_check_set_bep)) {
                file_put_contents($file_name_to_check_set_bep, "-");
                $hargaUntukAddPosisi = $priceAlert['entryPrice'] * 1.040;

                $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@ramdanriawan&text=Ayok set bep buy sekarang untuk {$priceAlert["time"]}, add posisi di: $hargaUntukAddPosisi&lang=en-GB-Standard-B&rpt=2", [

                ]);

            }

            // untuk add posisi buy
            elseif ($priceAlert['positionSide'] == 'LONG' && $priceAlert['currentPrice'] >= $priceAlert['entryPrice'] * 1.035 && !file_exists($file_name_to_check_add_position)) {
                file_put_contents($file_name_to_check_add_position, "-");
                $hargaUntukAddPosisi = $priceAlert['entryPrice'] * 1.040;

                $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@ramdanriawan&text=Ayok add position buy sekarang untuk {$priceAlert["time"]} diharga $hargaUntukAddPosisi&lang=en-GB-Standard-B&rpt=2", [

                ]);
            }

            // untuk set bep sell
            elseif ($priceAlert['positionSide'] == 'SHORT' && $priceAlert['currentPrice'] <= $priceAlert['entryPrice'] * 0.981 && !file_exists($file_name_to_check_set_bep)) {
                file_put_contents($file_name_to_check_set_bep, "-");
                $hargaUntukAddPosisi = $priceAlert['entryPrice'] * 0.960;

                $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@ramdanriawan&text=Ayok set bep sell sekarang untuk {$priceAlert["time"]}, add posisi di: $hargaUntukAddPosisi&lang=en-GB-Standard-B&rpt=2", [

                ]);
            }
            
            // untuk add posisi sell
            elseif ($priceAlert['positionSide'] == 'SHORT' && $priceAlert['currentPrice'] <= $priceAlert['entryPrice'] * 0.965 && !file_exists($file_name_to_check_add_position)) {
                file_put_contents($file_name_to_check_add_position, "-");
                $hargaUntukAddPosisi = $priceAlert['entryPrice'] * 0.960;
                $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@ramdanriawan&text=Ayok add position sell sekarang untuk {$priceAlert["time"]} diharga $hargaUntukAddPosisi&lang=en-GB-Standard-B&rpt=2", [

                ]);

            }
        }
    }

    public function test()
    {
        try {
            // // for open position
            // // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // $jayParsedAry = [
            //     "fundType" => 1,
            //     "largeSpreadRate" => 0,
            //     "leverTimes" => 1,
            //     "margin" => 2,
            //     "marginCoinName" => "USDT",
            //     "marketFactor" => 1.026771,
            //     "orderType" => 0,
            //     "price" => 0.756,
            //     "profitLossRateDto" => [
            //         "stopProfitRate" => 60,
            //         "stopLossRate" => 15
            //     ],
            //     "quotationCoinId" => 22,
            //     "spreadRate" => 0.00084146,
            //     "stopLossPrice" => -1,
            //     "stopProfitPrice" => -1,
            //     "upRatio" => 0.6
            // ];

            // // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // $ch = curl_init();

            // curl_setopt($ch, CURLOPT_URL, 'https://api-app.we-api.com/api/v2/contract/order/open');
            // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            // curl_setopt($ch, CURLOPT_POST, 1);
            // curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($jayParsedAry));
            // curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

            // $headers = array();
            // $headers[] = 'Authority: api-app.we-api.com';
            // $headers[] = 'Accept: application/json, text/plain, */*';
            // $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
            // $headers[] = 'App_version: 4.58.41';
            // $headers[] = 'Appid: 30004';
            // $headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';
            // $headers[] = 'Channel: official';
            // $headers[] = 'Content-Type: application/json';
            // $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
            // $headers[] = 'Lang: en';
            // $headers[] = 'Mainappid: 10009';
            // $headers[] = 'Origin: https://bingx.com';
            // $headers[] = 'Platformid: 30';
            // $headers[] = 'Sec-Ch-Ua: ^^Not_A';
            // $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
            // $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
            // $headers[] = 'Sec-Fetch-Dest: empty';
            // $headers[] = 'Sec-Fetch-Mode: cors';
            // $headers[] = 'Sec-Fetch-Site: cross-site';
            // $headers[] = 'Sign: F457F9A610D64DE50F49B3CC512492C40B09F7996BDF135A945E8827CFC336F3';
            // $headers[] = 'Timestamp: 1675420241812';
            // $headers[] = 'Timezone: 7';
            // $headers[] = 'Traceid: cbbf4d4e-0880-4c4d-95b9-c1f7a372ed9b';
            // $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
            // $headers[] = 'Visitorid: 2LgGccSJZrOi5YLy16kE';
            // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            // dd($json = curl_exec($ch));
            // $result = json_decode($json);

            // if (curl_errno($ch)) {
            //     echo 'Error:' . curl_error($ch);
            // }

            // for delegation
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // $jayParsedAry = [
            //     "balanceDirection" => 1, 
            //     "delegatePrice" => "0.757", 
            //     "fundType" => 1, 
            //     "largeSpreadRate" => 0, 
            //     "leverTimes" => 1, 
            //     "margin" => 2, 
            //     "marginCoinName" => "USDT", 
            //     "marketFactor" => 1.026771, 
            //     "orderType" => "0", 
            //     "price" => 0.756473, 
            //     "profitLossRateDto" => [
            //             "stopProfitRate" => "20", 
            //             "stopLossRate" => "20" 
            //         ], 
            //     "quotationCoinId" => 22, 
            //     "spreadRate" => 0.00084406, 
            //     "stopLossPrice" => -1, 
            //     "stopProfitPrice" => -1, 
            //     "upRatio" => 0.6 
            // ]; 

            // $ch = curl_init();

            // curl_setopt($ch, CURLOPT_URL, 'https://api-app.we-api.com/api/v2/contract/order/delegation');
            // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            // curl_setopt($ch, CURLOPT_POST, 1);
            // curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode( $jayParsedAry));
            // curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

            // $headers = array();
            // $headers[] = 'Authority: api-app.we-api.com';
            // $headers[] = 'Accept: application/json, text/plain, */*';
            // $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
            // $headers[] = 'App_version: 4.58.41';
            // $headers[] = 'Appid: 30004';
            // $headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';
            // $headers[] = 'Channel: official';
            // $headers[] = 'Content-Type: application/json';
            // $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
            // $headers[] = 'Lang: en';
            // $headers[] = 'Mainappid: 10009';
            // $headers[] = 'Origin: https://bingx.com';
            // $headers[] = 'Platformid: 30';
            // $headers[] = 'Sec-Ch-Ua: ^^Not_A';
            // $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
            // $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
            // $headers[] = 'Sec-Fetch-Dest: empty';
            // $headers[] = 'Sec-Fetch-Mode: cors';
            // $headers[] = 'Sec-Fetch-Site: cross-site';
            // $headers[] = 'Sign: B597BB9A764626B660011E352D297AA44B37514A15C75FC1201D8810524EEB63';
            // $headers[] = 'Timestamp: 1675423323993';
            // $headers[] = 'Timezone: 7';
            // $headers[] = 'Traceid: d3afb33d-9770-470c-a615-0d971b47c26c';
            // $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
            // $headers[] = 'Visitorid: 2LgGccSJZrOi5YLy16kE';
            // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            // dd($result = curl_exec($ch));
            // if (curl_errno($ch)) {
            //     echo 'Error:' . curl_error($ch);
            // }
            // curl_close($ch);


            // untuk melakukan set bep (gak bisa jalan)
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // $ch = curl_init();

            // curl_setopt($ch, CURLOPT_URL, 'https://bingx.com/api/v1/contract/profit-loss/modify');
            // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            // curl_setopt($ch, CURLOPT_POST, 1);
            // curl_setopt($ch, CURLOPT_POSTFIELDS, "^{^^id^^\":45274360,^^\"orderMargin^^\":2,^^\"orderNo^^\":^^\"1139053650155536390^^\",^^\"marginCoinName^^\":^^\"USDT^^\",^^\"type^^\":1,^^\"stopBy^^\":^^\"price^^\",^^\"margin^^\":0,^^\"stopPrice^^\":^^\"0.72^^\",^^\"stopRate^^\":-1,^^\"closeStyle^^\":1,^^\"logTxt^^\":^^\"0.72^^\"^}\"");
            // curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

            // $headers = array();
            // $headers[] = 'Authority: bingx.com';
            // $headers[] = 'Accept: application/json, text/plain, */*';
            // $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
            // $headers[] = 'App_version: 4.58.41';
            // $headers[] = 'Appid: 30004';
            // $headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';
            // $headers[] = 'Channel: official';
            // $headers[] = 'Content-Type: application/json';
            // $headers[] = 'Cookie: uuid=fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24; _bl_uid=jXlq8bgh7g7dgObp9l6jjRhaOds6; _fbp=fb.1.1670037699689.811336712; _ym_uid=1670037700989931251; _ym_d=1670037700; _gcl_au=1.1.600310863.1670135275; __zlcmid=1DGlQMk7jxdKe8m; kline_time_zone=8; uid=916855630822957058; _iidt=eLDTnVZYYLmHSP6+jiF0DWBcLOYCHbbo95GLOXMsyVxxQIXVqTg73RbfKlethu/xDfiDA53iUTTxsw==; _vid_t=KAM8G2lc/sOtydmD246FPldnDk28yW3j6Hzm2BNBL9img6j4xY3vCvxiFnNs0y7vyYDr2r75/t31IA==; visitorPId=2LgGccSJZrOi5YLy16kE; _ym_isad=2; locale=en-us; _gid=GA1.2.233687560.1675402674; user_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ; showKo=0; __cfruid=efc1b78d508f175c31301177a1bd61018a9d833c-1675418302; _cfuvid=XZEbmCdjE0lN8zKYlCDPHiXkB9r8.Oo79mXCgv0VJmw-1675420371732-0-604800000; __cf_bm=UvupwVd8jcYZ5Xn9fk5PPnFOu7tFGXlfKbuKHt2Uz5Q-1675427293-0-Ae+5kRvre4HclDR6lvWG2af3AlQ7Wle48t8FG0x4WGQM3yLhBlgzpgdcF+Eay1okGAVYBdPpHgh/5rpfhZO4LxU=; _ga_F8FPFG5ZCL=GS1.1.1675418011.56.1.1675427686.0.0.0; _ga_GH1NE7LJK0=GS1.1.1675418011.56.1.1675427686.0.0.0; lastCheckSessionAt=1675427687603; _ga=GA1.2.1374162158.1670037692; tokenExpiredAt=1675470893316; showKo=0; network_delay=349';
            // $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
            // $headers[] = 'Lang: en';
            // $headers[] = 'Mainappid: 10009';
            // $headers[] = 'Origin: https://bingx.com';
            // $headers[] = 'Platformid: 30';
            // $headers[] = 'Sec-Ch-Ua: ^^Not_A';
            // $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
            // $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
            // $headers[] = 'Sec-Fetch-Dest: empty';
            // $headers[] = 'Sec-Fetch-Mode: cors';
            // $headers[] = 'Sec-Fetch-Site: same-origin';
            // $headers[] = 'Sign: CB0B06E4FB16FC12E18F1FB7ACEC5B6F9F668FD4DB672913673E3AE96CD203A2';
            // $headers[] = 'Timestamp: 1675427808833';
            // $headers[] = 'Timezone: 7';
            // $headers[] = 'Traceid: 6793cf62-c7e0-4598-98c9-f1a6df68a585';
            // $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
            // $headers[] = 'Visitorid: 2LgGccSJZrOi5YLy16kE';
            // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            // dd($result = curl_exec($ch));
            // if (curl_errno($ch)) {
            //     echo 'Error:' . curl_error($ch);
            // }
            // curl_close($ch);

            // check token expired
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            // $ch = curl_init();

            // curl_setopt($ch, CURLOPT_URL, 'https://api-app.qq-os.com/api/v1/users/personal/information');
            // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            // curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

            // curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

            // $headers = array();
            // $headers[] = 'Authority: api-app.qq-os.com';
            // $headers[] = 'Accept: application/json, text/plain, */*';
            // $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
            // $headers[] = 'App_version: 4.58.41';
            // $headers[] = 'Appid: 30004';
            // $headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';
            // $headers[] = 'Channel: official';
            // $headers[] = 'Cookie: __cfruid=1f6a649f274cb40edefa2221cd1a2ae3fcff7b47-1675425945; __cf_bm=.9mgr2ShMR8LZ87Zipq_pDfEuSE196QZ3xlqbWvxsvg-1675426890-0-AYXlBh5XYkhqeyu+B8LeS2pvniawV+9BkDyt/fpkKbv0sKzw9PcieXJcXHhSZu9laxWrKQmDPMM9qQyd6gU4yBE=';
            // $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
            // $headers[] = 'Lang: en';
            // $headers[] = 'Mainappid: 10009';
            // $headers[] = 'Origin: https://bingx.com';
            // $headers[] = 'Platformid: 30';
            // $headers[] = 'Sec-Ch-Ua: ^^Not_A';
            // $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
            // $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
            // $headers[] = 'Sec-Fetch-Dest: empty';
            // $headers[] = 'Sec-Fetch-Mode: cors';
            // $headers[] = 'Sec-Fetch-Site: cross-site';
            // $headers[] = 'Sign: CA8AF8AEA0C0D157032AAC81BD8591825E6716B27996B73DF62AB08683DEEBDD';
            // $headers[] = 'Timestamp: 1675427530116';
            // $headers[] = 'Timezone: 7';
            // $headers[] = 'Traceid: bde333be-567d-474a-bb73-d538b2467e9c';
            // $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
            // $headers[] = 'Visitorid: 2LgGccSJZrOi5YLy16kE';
            // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            // $result = curl_exec($ch);
            // if (curl_errno($ch)) {
            //     echo 'Error:' . curl_error($ch);
            // }
            // curl_close($ch);

            // header('content-type: application/json');

            // die($result);
        } catch (\Throwable $t) {
            dd($t->getMessage());
        }
    }

    public function javascriptSound()
    {
        echo "
        <script>
        let audio = new Audio('/beep.mp3');

        for (let i = 0; i < 100; i++) {

            setTimeout(() => {

                audio.play();
            }, 5000 * i);
        }
        </script>";
    }

    // bisa
    public function checkTokenExpired()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.qq-os.com/api/v1/users/personal/information');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Authority: api-app.qq-os.com';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
        $headers[] = 'App_version: 4.58.41';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Authorization: Bearer ' . $this->token;
        $headers[] = 'Channel: official';
        $headers[] = 'Cookie: __cfruid=fd982c4c717417e5353e27656fb75f214d6c986f-1675508060; __cf_bm=KHC6djJ8E7QNi.IYySb2ArYD0GqKdCzjN.S.OFBVHmI-1675513984-0-Acx93Gj2RR7+u8jxJBDEl0X4dwgDsu3VRqr9iK4r8XXO1bf9q4amw2x7IlDN+iMBLucnawesI+iBUoZ4N8W6dfI=';
        $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
        $headers[] = 'Lang: en';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Origin: https://bingx.com';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Sec-Ch-Ua: ^^Not_A';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
        $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: cross-site';
        $headers[] = 'Sign: DD1280E9EB1B3A3BBEDB484BA4DF1B3D510B92C0DF321AB5555867E1A4AE7649';
        $headers[] = 'Timestamp: 1675514146716';
        $headers[] = 'Timezone: 7';
        $headers[] = 'Traceid: fc7b62f0-3390-4b05-aac1-e7347a526c34';
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
        $headers[] = 'Visitorid: -1';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        header('content-type: application/json');

        die($result);
    }

    public function client()
    {

        return new Client();
    }

    // 
    public function tokenExpired()
    {
        try {
            $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=mohon update token, sudah expired!&lang=en-GB-Standard-B&rpt=2", [

            ]);

            $this->sendTelegramMessage2("Token habis");
        } catch (\Throwable $t) {

            die($t->getMessage());
        }

        echo "<script>window.close();</script>";
    }

    //
    public function getSpread()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.we-api.com/api/v1/contract/spread?quotationCoinId=22&marginCoinName=USDT');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Authority: api-app.we-api.com';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
        $headers[] = 'App_version: 4.58.41';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Authorization: Bearer ' . $this->token;
        $headers[] = 'Channel: official';
        $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
        $headers[] = 'Lang: en';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Origin: https://bingx.com';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Sec-Ch-Ua: ^^Not_A';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
        $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: cross-site';
        $headers[] = 'Sign: 288DBCCDA9D0361A7E3C739917A2F905B76E6E88EDE8436EE688B7DEC7F2A910';
        $headers[] = 'Timestamp: 1675431552351';
        $headers[] = 'Timezone: 7';
        $headers[] = 'Traceid: fc65af3d-5823-4ace-a39f-9b4a702c742f';
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
        $headers[] = 'Visitorid: 2LgGccSJZrOi5YLy16kE';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result);
    }

    // karna kita gak bisa makai delegate karena di sign sama bingx, maka open market
    public function addPosition($order_no, $price, $leverage, $margin, $order_type, $take_profit_rate, $stop_loss_rate, $coin_id, $token_bearer)
    {
        if (!$this->isLive) {

            $this->javascriptSound();
        }

        if ($this->isLive) {
            $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Hayo tambah posisi untuk $order_no&lang=en-GB-Standard-B&rpt=2", [

            ]);
        }

        $file_name = "has_add_" . $order_no;

        if (file_exists($file_name)) {
            return;
        }

        try {
            $jayParsedAry = [
                "fundType" => 1,
                "largeSpreadRate" => 0,
                "leverTimes" => $leverage,
                "margin" => $margin,
                "marginCoinName" => "USDT",
                "marketFactor" => 1,
                "orderType" => $order_type,
                "price" => 0.767973,
                "profitLossRateDto" => [
                    "stopProfitRate" => $take_profit_rate,
                    "stopLossRate" => $stop_loss_rate
                ],
                "quotationCoinId" => $coin_id,
                "spreadRate" => 0.0008436,
                "stopLossPrice" => -1,
                "stopProfitPrice" => -1,
                "upRatio" => 0.6
            ];

            $curl = curl_init();

            curl_setopt_array(
                $curl,
                array(
                    CURLOPT_URL => 'https://api-app.qq-os.com/api/v2/contract/order/open',
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_ENCODING => '',
                    CURLOPT_MAXREDIRS => 10,
                    CURLOPT_TIMEOUT => 0,
                    CURLOPT_FOLLOWLOCATION => true,
                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                    CURLOPT_CUSTOMREQUEST => 'POST',
                    CURLOPT_POSTFIELDS => json_encode($jayParsedAry),
                    CURLOPT_HTTPHEADER => array(
                        'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
                        'mainAppId: 10009',
                        'Authorization: Bearer ' . $this->token,
                        'lang: en',
                        'platformId: 30',
                        'channel: official',
                        'timeZone: 7',
                        'sign: 39703235A8B435EF480B2681C423E39C63845D27AE3F13691BDAAB62640C8AAB',
                        'sec-ch-ua-platform: "Windows"',
                        'device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24',
                        'sec-ch-ua-mobile: ?0',
                        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
                        'Content-Type: application/json',
                        'traceId: bb7485fa-183e-498e-9463-c8439b6fa3a4',
                        'Accept: application/json, text/plain, */*',
                        'timestamp: 1675442847258',
                        'visitorId: 2LgGccSJZrOi5YLy16kE',
                        'appId: 30004',
                        'app_version: 4.58.41',
                        'Sec-Fetch-Site: cross-site',
                        'Sec-Fetch-Mode: cors',
                        'Sec-Fetch-Dest: empty',
                        'host: api-app.qq-os.com',
                        'Cookie: __cf_bm=hStvMr0vB0D8wV09CVb4PUrTxlUyFoRcG4d.SZ_3z4U-1675442487-0-AeY+4ZUrdfij/GSZ/OCJZiuxb0ocYS37U08dYzQQgk2hHF1vv1TDrEITnO9gpzB1JorhCffByYR021zlzW+2bcM=; __cfruid=05dcd70f2f8a684190f036dab42cfa5746bc0f30-1675442487'
                    ),
                )
            );

            $json = (curl_exec($curl));
            $result = json_decode($json);
            curl_close($curl);

            if ($result->code === 0) {
                $message = "posisi untuk pair $coin_id telah berhasil ditambah";
                $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=$message&lang=en-GB-Standard-B&rpt=2", [

                ]);

                file_put_contents($file_name, "-");

                $this->sendTelegramMessage2($message);
            } elseif ($result->code != 0) {
                $message = "posisi untuk pair $coin_id gagal ditambah";
                $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=$message&lang=en-GB-Standard-B&rpt=2", [

                ]);

                $this->sendTelegramMessage2($message);
            } else {

                $this->sendTelegramMessage2("Gagal menambah posisi");

                file_put_contents("gagal_tambah_posisi");
            }
        } catch (\Throwable $t) {
            $this->sendTelegramMessage2("Gagal menambah posisi");

            file_put_contents("gagal_tambah_posisi", $t->getMessage());
        }
    }

    public function checkUserPosition() {
        header('content-type: application/json');
        
        if(file_exists('membuka_posisi_dimulai')) {
            $membuka_posisi_dimulai = file_get_contents('membuka_posisi_dimulai');
    
            File::delete('membuka_posisi_dimulai');

    
            die($membuka_posisi_dimulai);
        } else {
            return response()->json([
                'success' => false,
            ]);
        }
    }

    public function openPosition(Request $request)
    {


        if (!$this->isLive) {

            $this->javascriptSound();
        }

        if ($this->isLive) {
            $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Hayo buka posisi&lang=en-GB-Standard-B&rpt=2", [

            ]);
        }

        echo "<script>window.close();</script>";

        die;
        start:
        file_put_contents("membuka_posisi_dimulai", json_encode($request->toArray()));

        try {
            // dsfdsfsdfsdfds sdfdsf

            $jayParsedAry = [
                "fundType" => 1,
                "largeSpreadRate" => 0,
                "leverTimes" => $this->leverage,
                "margin" => $this->margin,
                "marginCoinName" => "USDT",
                "marketFactor" => 1,
                "orderType" => $request->order_type,
                "price" => 0.767973,
                "profitLossRateDto" => [
                    "stopProfitRate" => $this->takeProfit,
                    "stopLossRate" => $this->stopLoss
                ],
                "quotationCoinId" => $this->koinId,
                "spreadRate" => 0.0008436,
                "stopLossPrice" => -1,
                "stopProfitPrice" => -1,
                "upRatio" => 0.6
            ];

            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, 'https://api-app.qq-os.com/api/v2/contract/order/open');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($jayParsedAry));
            curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

            $headers = array();
            $headers[] = 'Authority: api-app.qq-os.com';
            $headers[] = 'Accept: application/json, text/plain, */*';
            $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
            $headers[] = 'App_version: 4.58.41';
            $headers[] = 'Appid: 30004';
            $headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';
            $headers[] = 'Channel: official';
            $headers[] = 'Content-Type: application/json';
            $headers[] = 'Cookie: __cfruid=2e0351c02aa0af3237188c8bc7af29253838e576-1675597290; __cf_bm=aYvwXSLOLKr_wVrcTpt7mOTUhq7WXqnX49c4IHjDzV0-1675598374-0-ATpLp3oKNH34a9RUhPjCnHLl6ESmub6u9lVwt+krRaF+RFNygAh6UI46LuToxLSp9NBYwqr7nltrA9c+iZ7Q5SM=';
            $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
            $headers[] = 'Lang: en';
            $headers[] = 'Mainappid: 10009';
            $headers[] = 'Origin: https://bingx.com';
            $headers[] = 'Platformid: 30';
            $headers[] = 'Sec-Ch-Ua: ^^Not_A';
            $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
            $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
            $headers[] = 'Sec-Fetch-Dest: empty';
            $headers[] = 'Sec-Fetch-Mode: cors';
            $headers[] = 'Sec-Fetch-Site: cross-site';
            $headers[] = 'Sign: AF4F645B24F78BEC0AA483FD1DDD7413C128B33CDC1ABCACF2C45EF0B9FD4A7B';
            $headers[] = 'Timestamp: 1675598606605';
            $headers[] = 'Timezone: 7';
            $headers[] = 'Traceid: c4599f28-315d-4fdb-b058-fe76d72d07f8';
            $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
            $headers[] = 'Visitorid: -1';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $json = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }

            $result = json_decode($json);
            curl_close($ch);

            $requestData = json_encode($request->all());

            if ($result->code === 0) {
                $message = "posisi untuk pair {$request->get('pair')} telah berhasil dibuka";
                $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=$message&lang=en-GB-Standard-B&rpt={$request->get('numOfTelegramCallNotice')}", [

                ]);

                $this->sendTelegramMessage2($message);
                file_put_contents("posisi_berhasil_dibuka", "");
            } elseif ($result->code != 0) {
                $message = "posisi untuk pair {$request->get('pair')} gagal dibuka";

                $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=$message&lang=en-GB-Standard-B&rpt={$request->get('numOfTelegramCallNotice')}", [

                ]);

                $this->sendTelegramMessage2($message);

                file_put_contents("gagal_membuka_posisi", $json);

                // goto start;
            } else {
                file_put_contents("gagal_membuka_posisi", $json);
                $this->sendTelegramMessage2("gagal_membuka_posisi");
                // goto start;
            }
        } catch (\Throwable $t) {
            file_put_contents("gagal_membuka_posisi", $t->getMessage());

            $this->sendTelegramMessage2("gagal_membuka_posisi");

            dd($t->getMessage());

            // goto start;
        }
    }

    public function getOrders()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // Generated @ codebeautify.org
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.we-api.com/api/v3/contract/order/hold?fundType=1&pagingSize=10&pageId=0&marginCoinName=USDT&marginType=0&quotationCoinId=-1');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Authority: api-app.we-api.com';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Language: en-US,en;q=0.9,id;q=0.8';
        $headers[] = 'App_version: 4.58.41';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ';
        $headers[] = 'Channel: official';
        $headers[] = 'Device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24';
        $headers[] = 'Lang: en';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Origin: https://bingx.com';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Sec-Ch-Ua: ^^Not_A';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
        $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: cross-site';
        $headers[] = 'Sign: 3DE6AADAFE13A0F64CD56FDEDE09B69F0A4860A22C4AEB5918F759A6A8C9C534';
        $headers[] = 'Timestamp: 1675600302011';
        $headers[] = 'Timezone: 7';
        $headers[] = 'Traceid: 012dfa1f-d2e9-441d-a8f2-db59c2718c71';
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
        $headers[] = 'Visitorid: -1';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        dd($result = curl_exec($ch));
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result);
    }

    // gak di pakai
    public function getTriggerOrders()
    {

        return json_decode(exec("curl \"https://api-app.cmlucky.com/api/v1/contract/order/delegation/list?fundType=1&pagingSize=10&pageId=0&statusList=0&marginCoinName=usdt&getDelegation=0\" -H \"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0\" -H \"Accept: application/json, text/plain, */*\" -H \"Accept-Language: en-US,en;q=0.5\" -H \"Authorization: Bearer $this->token\" -H \"device_id: 2b97ef90-30ee-11ec-88fd-d3f61af02d3c\" -H \"platformId: 30\" -H \"channel: official\" -H \"app_version: 4.6.10\" -H \"lang: en\" -H \"appId: 30004\" -H \"mainAppId: 10009\" -H \"Timestamp: 1634798833122\" -H \"traceId: 43576502-61c2-40c5-abd2-4de679711f84\" -H \"Sign: C8D8C9C1F347B529349B550511F74BB4CB9AC3468AB64AEF115D49F55546B077\" -H \"Origin: https://bingbon.com\" -H \"Connection: keep-alive\" -H \"Cookie: __cfruid=b8a594bddb26dc818a5bae48c7fab9e09b58f1ef-1634773697; __cf_bm=Fi7.eDo4MKb4tJHs6QjR0Y1BBcxuV0yxwEeDFHcv2QQ-1634798150-0-Af21Jyp0ljs5Cc84DWb8eS1VUB4PEfgm/rbdsQUR1az4VU3dX2gA7H40tH3wLQ0ix9xWOFCOnuYj+5aqU+PuT8A=\" -H \"Sec-Fetch-Dest: empty\" -H \"Sec-Fetch-Mode: cors\" -H \"Sec-Fetch-Site: cross-site\" -H \"TE: trailers\""));
    }

    // gak di pakai
    public function cancelOrderBot($order)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.cmlucky.com/api/v1/contract/order/cancel/delegation');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
            'orderNo' => $order->orderNo
        ]));
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Encoding: *';
        $headers[] = 'Accept-Language: en-US,en;q=0.5';
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'Authorization: Bearer ' . $this->token;
        $headers[] = 'Device_id: 2b97ef90-30ee-11ec-88fd-d3f61af02d3c';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Channel: official';
        $headers[] = 'App_version: 4.7.1';
        $headers[] = 'Lang: en';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Timestamp: 1635751743997';
        $headers[] = 'Traceid: e0a4c23f-832e-4e7f-8b8e-940951061b51';
        $headers[] = 'Sign: 2B61DE53C81B6A5EE96368ADC2CDFF7B43CD370390C85B39FEE1069CC947D4C1';
        $headers[] = 'Origin: https://bingbon.com';
        $headers[] = 'Connection: keep-alive';
        $headers[] = "Cookie: uuid=2b97ef90-30ee-11ec-88fd-d3f61af02d3c; __zlcmid=16dkPu1KoK6xw0o; _gcl_au=1.1.969461259.1635043823; _ga=GA1.2.970725696.1635043824; __cfruid=71753a6ee9dd3d5fe9151b2d34a6a7e61d26ad6e-1635744414; user_token=$this->token; uid=916855630822957058; network_delay=245; __cf_bm=78NJX74S16n9YV2yWvV7DA2XoodBfT64wHLxtGMF2Vg-1635751628-0-AacXzfeLuXZlV0tLK6eW4WQZz5lqh0VA/tKvPcncQo+Wii7kyhgIJFCrV28Foh9K6TxtIZZMoL4J46oAfgS3w0M=; _gid=GA1.2.524811945.1635744537; _gat_gtag_UA_158549354_1=1";
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: same-site';
        $headers[] = 'Te: trailers';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
    }

    // gak di pakai
    public function cancelOrder()
    {
        start:
        try {
            foreach ($this->getTriggerOrders()->data->result as $order) {

                // posisi long
                if ($order->currentPrice > ($order->delegatePrice * 1.02) && $order->orderType === 0) {
                    $this->cancelOrderBot($order);
                }

                // posisi short
                if ($order->currentPrice < ($order->delegatePrice * 0.98) && $order->orderType === 1) {
                    $this->cancelOrderBot($order);
                }
            }
        } catch (\Throwable $t) {
            $order2 = json_encode($order);
            $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=gagal set BEP&lang=en-GB-Standard-B&rpt=2", [

            ]);

            // goto start;
        }
    }

    // blm bisaaaa
    public function setBepBot($order_id, $stop_loss_price, $stop_profit_price, $stop_profit_rate, $stop_loss_rate, $id)
    {

        if (!$this->isLive) {

            $this->javascriptSound();
        }

        if ($this->isLive) {
            $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@ramdanriawan&text=Ayok set bepe sekarang untuk $order_id&lang=en-GB-Standard-B&rpt=2", [

            ]);
        }

        // // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // $postFields = json_encode([
        //     'id' => $id,
        //     'orderMargin' => $this->margin,
        //     'orderNo' => "$order_id",
        //     'marginCoinName' => 'USDT',
        //     'type' => 1,
        //     'stopBy' => 'price',
        //     'margin' => 0,
        //     'stopPrice' => $stop_loss_price,
        //     'stopRate' => -1,
        //     'closeStyle' => 1,
        //     'logTxt' => $stop_loss_price,
        // ]);

        // $curl = curl_init();

        // curl_setopt_array($curl, array(
        //     CURLOPT_URL => 'https://api-app.qq-os.com/api/v1/contract/profit-loss/modify',
        //     CURLOPT_RETURNTRANSFER => true,
        //     CURLOPT_ENCODING => '',
        //     CURLOPT_MAXREDIRS => 10,
        //     CURLOPT_TIMEOUT => 0,
        //     CURLOPT_FOLLOWLOCATION => true,
        //     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        //     CURLOPT_CUSTOMREQUEST => 'POST',
        //     CURLOPT_POSTFIELDS => "{\"id\":$id,\"orderMargin\":2,\"orderNo\":\"$order_id\",\"marginCoinName\":\"USDT\",\"type\":1,\"stopBy\":\"percent\",\"margin\":0,\"stopPrice\":-1,\"stopRate\":\"16\",\"closeStyle\":1,\"logTxt\":\"16%\"}",
        //     CURLOPT_HTTPHEADER => array(
        //         'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
        //         'mainAppId: 10009',
        //         'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTY4NTU2MzA4MjI5NTcwNTgiLCJleHAiOjE2NzU2NjIyNTJ9.Fd5p3rT27Ueu-z0YVydSL-rfIXu_771SzKpstGsxeWnZoeGKQCWRxHVF-SYSdcj7_TVItrIpVXEgHSCgWFkvwQ',
        //         'lang: en',
        //         'platformId: 30',
        //         'channel: official',
        //         'timeZone: 7',
        //         'sign: C68A3E97F87DC5C6F5793CBEE931675C62C2BBADAF032854C96B7883C823B84B',
        //         'sec-ch-ua-platform: "Windows"',
        //         'device_id: fa3f1a89-6dd5-40bb-9772-13dc7ce6ff24',
        //         'sec-ch-ua-mobile: ?0',
        //         'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
        //         'Content-Type: application/json',
        //         'traceId: 88a4a19f-4e8c-48c4-ba25-76319925c4f2',
        //         'Accept: application/json, text/plain, */*',
        //         'timestamp: 1675443388580',
        //         'visitorId: 2LgGccSJZrOi5YLy16kE',
        //         'appId: 30004',
        //         'app_version: 4.58.41',
        //         'Sec-Fetch-Site: cross-site',
        //         'Sec-Fetch-Mode: cors',
        //         'Sec-Fetch-Dest: empty',
        //         'host: api-app.qq-os.com',
        //         'Cookie: __cf_bm=0XcDCSEQvjeLlwPYfA7sGuayCzF5f9FCub56.UZh3KQ-1675446880-0-AeGf90m/8ROSDIqCJFf79Bv/SGG9CrCLBys0qOgnlkl7srvy2Z+of0wK99ufqH4BnF36yazLdqVmtLwAR34QAB8=; __cfruid=05dcd70f2f8a684190f036dab42cfa5746bc0f30-1675442487'
        //     ),
        // )
        // );

        // dd($response = curl_exec($curl));

        // curl_close($curl);

        // $this->sendTelegramMessage2("Berhasil set bep untuk id: " . $order_id);
        // $this->sendTelegramMessage2("Ayoo set bep sekarang sebelum terlambat!!!!!");
    }

    public function setBep()
    {
        set_time_limit(0);

        start:

        try {
            $orders = $this->getOrders()->data->orders;

            if (!count($orders)) {
                die("No orders");
            }
        } catch (\Throwable $t) {
            return "Terjadi kesalahan saat ambil orders: {$t->getMessage()}";
        }

        try {
            foreach ($orders as $order) {
                $order2 = json_encode($order);
                $fileNameSetBep = "has_set_bep_" . $order->orderNo;
                $fileNameHasAddPosition = "has_add_position_" . $order->orderNo;
                $addPosition = ($order->displayPrice * 1.04);

                // posisi long
                if ($order->profitLossInfo->profitConfig->stopRate == $this->takeProfit && $order->currentPrice > ($order->displayPrice * 1.0178) && $order->orderType === 0 && !file_exists($fileNameSetBep) && !file_exists($fileNameHasAddPosition)) {
                    file_put_contents("set_bep_dimulai_posisi_long1", $order2);
                    if (file_put_contents($fileNameSetBep, "-") !== false) {
                        $this->setBepBot($order->orderNo, $order->displayPrice, -1, $this->takeProfit, -1, $order->profitLossInfo->lossConfig->id);

                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Berhasil set bep&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    } else {
                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Gagal set bep (membuat file)&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    }
                }

                if ($order->profitLossInfo->profitConfig->stopRate == $this->takeProfit && $order->currentPrice > ($order->displayPrice * 1.0380) && $order->orderType === 0 && !file_exists($fileNameHasAddPosition)) {
                    file_put_contents("set_bep_dimulai_posisi_long2", $order2);
                    $addPosition = ($order->displayPrice * 1.04);
                    $sidePosition = ($order->displayPrice * 1.02);

                    if (file_put_contents($fileNameHasAddPosition, "-") !== false) {
                        $this->addPosition($order->orderNo, $addPosition, $this->leverage, $this->margin, $order->orderType, $this->takeProfiteOnAddPosition, $this->stopLossOnAddPosition, $this->koinId, $this->token);
                        $this->setBepBot($order->orderNo, $sidePosition, -1, $this->takeProfit, -1, $order->profitLossInfo->lossConfig->id);

                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Berhasil menambah posisi bep&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    } else {
                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Gagal menambah posisi (membuat file)&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    }
                }

                // posisi short
                if ($order->profitLossInfo->profitConfig->stopRate == $this->takeProfit && $order->currentPrice < ($order->displayPrice * 0.982) && $order->orderType === 1 && !file_exists($fileNameSetBep) && !file_exists($fileNameHasAddPosition)) {
                    file_put_contents("set_bep_dimulai_posisi_short1", $order2);
                    if (file_put_contents($fileNameSetBep, "-") !== false) {
                        $this->setBepBot($order->orderNo, $order->displayPrice, -1, $this->takeProfit, -1, $order->profitLossInfo->lossConfig->id);

                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Berhasil set bep&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    } else {
                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Gagal set bep (membuat file)&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    }
                }

                if ($order->profitLossInfo->profitConfig->stopRate == $this->takeProfit && $order->currentPrice < ($order->displayPrice * 0.9620) && $order->orderType === 1 && !file_exists($fileNameHasAddPosition)) {
                    file_put_contents("set_bep_dimulai_short_2", $order2);
                    $addPosition = ($order->displayPrice * 0.960);
                    $sidePosition = ($order->displayPrice * 0.980);

                    if (file_put_contents($fileNameHasAddPosition, "-") !== false) {
                        $this->addPosition($order->orderNo, $addPosition, $this->leverage, $this->margin, $order->orderType, $this->takeProfiteOnAddPosition, $this->stopLossOnAddPosition, $this->koindId, $this->token);
                        $this->setBepBot($order->orderNo, $sidePosition, -1, $this->takeProfit, -1, $order->profitLossInfo->lossConfig->id);

                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Berhasil menambah posisi bep&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    } else {
                        $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=Gagal menambah posisi bep (membuat file)&lang=en-GB-Standard-B&rpt=2", [

                        ]);
                    }
                }
            }

            return "Semuanya sudah di cek";
        } catch (\Throwable $t) {
            file_put_contents("error_set_bep_" . time(), "Error : " . now()->toDateTimeString() . " " . $t->getMessage());

            $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=gagal set BEP&lang=en-GB-Standard-B&rpt=2", [

            ]);

            // goto start;
        }
    }

    public function position(Request $request)
    {

        $this->sendTelegramMessage2("logika membuka posisi terdeteksi (server)");
        start:

        file_put_contents("logika_membuka_posisi_terdeteksi", json_encode($request->toArray()));

        try {
            Artisan::call("view:clear");

            $filename = "{$request->logic_name}_" . preg_replace("/\/|\:/", "_", $request->timeToOpenPosition);

            if (in_array($request->logicName, ["isLogic1", "psr_sell_macd_blue_bb_between_macd_blue", "psr_buy_macd_red_bb_between_macd_red"])) {
                if (file_exists($filename)) {

                    goto end;
                }

                file_put_contents($filename, '-');
                $this->openPosition($request);
            } else {

                if ($request->logicName == "psr_sell_macd_red_bb_between_macd_red") {
                    $filename_time_before1 = "psr_buy_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_sell_macd_red_bb_between_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_buy_macd_blue_bb_between_macd_blue") {
                    $filename_time_before1 = "psr_sell_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "bb_between_macd_cross_to_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_buy_macd_blue_bb_between_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                    if (file_exists($filename_time_before2)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before2)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_buy_macd_red") {
                    $filename_time_before1 = "bb_between_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "bb_between_macd_cross_to_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_buy_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1) || file_exists($filename_time_before2)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_buy_macd_cross") {
                    $filename_time_before1 = "bb_between_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_buy_macd_cross_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_sell_macd_cross_bb_between_macd_cross_to_blue") {
                    $filename_time_detect = "psr_sell_macd_cross_bb_between_macd_cross_to_blue_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (!file_exists($filename_time_detect)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_buy_macd_blue") {
                    $filename_time_before1 = "bb_between_macd_cross_to_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "bb_between_macd_cross_to_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before3 = "psr_sell_macd_cross_bb_between_macd_cross_to_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);

                    $filename_time_detect = "psr_buy_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                    if (file_exists($filename_time_before2)) {
                        $request->request->add(['order_type' => 0]);
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before2)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                    if (file_exists($filename_time_before3)) {
                        $request->request->add(['order_type' => 0]);
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before2)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                } elseif ($request->logicName == "psr_sell_macd_blue") {
                    $filename_time_before1 = "bb_between_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_sell_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_sell_macd_cross") {
                    $filename_time_before1 = "bb_between_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_sell_macd_cross_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "psr_sell_macd_red") {
                    $filename_time_before1 = "bb_between_macd_cross_to_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "psr_sell_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "bb_between_macd_blue") {
                    $filename_time_before1 = "psr_buy_macd_cross_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "psr_sell_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "bb_between_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);

                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                    // kalo sell
                    if (file_exists($filename_time_before2)) {

                        $request->request->add(['order_type' => 1]);

                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, '-');
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, '-');
                    }

                } elseif ($request->logicName == "bb_between_macd_cross_to_blue") {
                    $filename_time_before1 = "psr_buy_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "psr_buy_macd_cross_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "bb_between_macd_cross_to_blue_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1) || file_exists($filename_time_before2)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                } elseif ($request->logicName == "bb_between_macd_cross_to_red") {
                    $filename_time_before1 = "psr_sell_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "psr_sell_macd_blue_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before3 = "psr_sell_macd_cross_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "bb_between_macd_cross_to_red_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1) || file_exists($filename_time_before2) || file_exists($filename_time_before3)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }


                    // logic tambahan
                    if (file_exists($filename_time_before2)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    }
                } elseif ($request->logicName == "bb_between_macd_red") {
                    $filename_time_before1 = "psr_sell_macd_cross_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_before2 = "psr_buy_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeBefore);
                    $filename_time_detect = "bb_between_macd_red_" . preg_replace("/\/|\:/", "_", $request->timeDetect);

                    if (file_exists($filename_time_before1)) {
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before1)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                    if (file_exists($filename_time_before2)) {
                        $request->request->add(['order_type' => 0]);
                        $this->openPosition($request);
                        file_put_contents($filename_time_detect, $request->order_type);
                    } elseif (!file_exists($filename_time_before2)) {
                        file_put_contents($filename_time_detect, $request->order_type);
                    }

                }
            }

            end:
            Artisan::call("view:clear");
            echo "<script>window.close();</script>";
        } catch (\Throwable $t) {
            file_put_contents("error_" . time(), "Error : " . now()->toDateTimeString() . " " . $t->getMessage());

            $response = $this->client()->request('GET', "https://api.callmebot.com/start.php?user=@ramdanriawan&text=gagal open position&lang=en-GB-Standard-B&rpt=2", [

            ]);

            // goto start;
        }

    }

    public function sendTelegramMessage(Request $request)
    {
        //        $response = $this->client()->request('GET', "https://api.callmebot.com/text.php?user=@{$request->post('telegram_id')}&text={$request->post('message')}", [
//
//        ]);

        $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@{$request->post('telegram_id')}&text={$request->post('message')}&lang=en-GB-Standard-B&rpt={$request->post('repeat')}", [

        ]);

        return json_encode([
            'status' => 'success'
        ]);
    }

    public function sendTelegramMessage2($message)
    {
        $response = $this->client()->request('GET', "https://api.callmebot.com/text.php?user=@ramdanriawan&text=$message", [

        ]);
        //
//        $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@ramdanriawan&text=$message&lang=en-GB-Standard-B&rpt=2", [
//
//        ]);

        return json_encode([
            'status' => 'success'
        ]);
    }

    public function callTelegramMessage(Request $request)
    {
        $response = $this->client()->request('GET', "http://api.callmebot.com/start.php?user=@{$request->get('telegram_id')}&text={$request->get('message')}&lang=en-GB-Standard-B&rpt={$request->get('repeat')}", [

        ]);

        echo "<script>window.close()</script>";
    }

    public function gantiToken(Request $request)
    {
        $file_watch_js = file_get_contents("watch.js");
        $file_bot_trading = file_get_contents((__DIR__ . '/BotTradingController.php'));

        $command1 = "ps -ef | grep 'java' | grep -v grep | awk '{print $2}' | xargs -r kill -9";
        $command2 = "ps -ef | grep 'geckodriver' | grep -v grep | awk '{print $2}' | xargs -r kill -9";
        $command3 = "ps -ef | grep 'firefox' | grep -v grep | awk '{print $2}' | xargs -r kill -9";

        $token_lama = $request->token_lama;
        $token_baru = $request->token_baru;

        $file_watch_js = str_replace($token_lama, $token_baru, $file_watch_js);
        $file_bot_trading = str_replace($token_lama, $token_baru, $file_bot_trading);
        file_put_contents('watch.js', $file_watch_js);
        file_put_contents((__DIR__ . '/BotTradingController.php'), $file_bot_trading);

        //
        $host = "185.211.5.241";
        $username = "root";
        $password = "mautauajakamu98";

        $ssh = new SSH2($host);
        if (!$ssh->login($username, $password)) {
            exec("curl 'https://bikinaplikasi.dev/bot-trading/call-telegram-message?telegram_id=ramdanriawan&message=login ssh untuk ganti token gagal'");
        } else {

            $ssh->exec($command1);
            $ssh->exec($command2);
            $ssh->exec($command3);
        }

        die("https://bikinaplikasi.dev/bot-trading/ganti-token?token_lama=$token_baru&token_baru=");
    }


    public function gantiMargin(Request $request)
    {
        $file_watch_js = file_get_contents("watch.js");
        $file_bot_trading = file_get_contents((__DIR__ . '/BotTradingController.php'));

        $command1 = "ps -ef | grep 'java' | grep -v grep | awk '{print $2}' | xargs -r kill -9";
        $command2 = "ps -ef | grep 'geckodriver' | grep -v grep | awk '{print $2}' | xargs -r kill -9";
        $command3 = "ps -ef | grep 'firefox' | grep -v grep | awk '{print $2}' | xargs -r kill -9";

        $margin_lama = $request->margin_lama;
        $margin_baru = $request->margin_baru;

        $file_watch_js = str_replace($margin_lama, $margin_baru, $file_watch_js);
        $file_bot_trading = str_replace($margin_lama, $margin_baru, $file_bot_trading);
        file_put_contents('watch.js', $file_watch_js);
        file_put_contents((__DIR__ . '/BotTradingController.php'), $file_bot_trading);

        //
        $host = "185.211.5.241";
        $username = "root";
        $password = "mautauajakamu98";

        $ssh = new SSH2($host);
        if (!$ssh->login($username, $password)) {
            exec("curl 'https://bikinaplikasi.dev/bot-trading/call-telegram-message?telegram_id=ramdanriawan&message=login ssh untuk ganti token gagal'");
        } else {

            $ssh->exec($command1);
            $ssh->exec($command2);
            $ssh->exec($command3);
        }

        die("oke");
    }

    public function updateMargin(Request $request)
    {

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.qq-os.com/api/v1/assets/0');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Authority: api-app.qq-os.com';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Encoding: *';
        $headers[] = 'Accept-Language: en-US,en;q=0.9';
        $headers[] = 'App_version: 4.33.1';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Authorization: Bearer ' . $this->token;
        $headers[] = 'Channel: official';
        $headers[] = 'Cookie: __cfruid=8dfdc83610483b6c48eac7a18c71c3775f9d1a86-1657151225; __cf_bm=o3Y3JfeLfAKk5JlQbddeHC16Qa8CTR5DmNqHN4JhrSc-1657153162-0-AREzBhzDdokaOZKZCRzr/h7SvKwXplTWsycoN9K7V1MySb22BsbQcM1f7IIANoShT5PC7Nroz0KyydvefvF5BBg=';
        $headers[] = 'Device_id: e20b78f0-b177-11ec-960f-c9bb23bf51ff';
        $headers[] = 'Lang: id-ID';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Origin: https://bingx.com';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Sec-Ch-Ua: ^^.Not/A)Brand^^\";v=^^\"99^^\",';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
        $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: cross-site';
        $headers[] = 'Sign: 967058CF0503EFB6C71E50E545D42A72F481A9D147B5C8E09128B1817B5C0792';
        $headers[] = 'Timestamp: 1657153454729';
        $headers[] = 'Timezone: 7';
        $headers[] = 'Traceid: 52003d3f-6c54-44ec-832e-9471c4c67240';
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        header('content-type: application/json');

        $result = json_decode($result);

        sleep(5);

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.qq-os.com/api/v2/contract/order/history?fundType=1&pagingSize=10&pageId=0&marginCoinName=usdt&marginType=0');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Authority: api-app.qq-os.com';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Encoding: *';
        $headers[] = 'Accept-Language: en-US,en;q=0.9';
        $headers[] = 'App_version: 4.33.1';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Authorization: Bearer ' . $this->token;
        $headers[] = 'Channel: official';
        $headers[] = 'Cookie: __cfruid=8dfdc83610483b6c48eac7a18c71c3775f9d1a86-1657151225; __cf_bm=o3Y3JfeLfAKk5JlQbddeHC16Qa8CTR5DmNqHN4JhrSc-1657153162-0-AREzBhzDdokaOZKZCRzr/h7SvKwXplTWsycoN9K7V1MySb22BsbQcM1f7IIANoShT5PC7Nroz0KyydvefvF5BBg=';
        $headers[] = 'Device_id: e20b78f0-b177-11ec-960f-c9bb23bf51ff';
        $headers[] = 'Lang: id-ID';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Origin: https://bingx.com';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Sec-Ch-Ua: ^^.Not/A)Brand^^\";v=^^\"99^^\",';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
        $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: cross-site';
        $headers[] = 'Sign: 967058CF0503EFB6C71E50E545D42A72F481A9D147B5C8E09128B1817B5C0792';
        $headers[] = 'Timestamp: 1657153454729';
        $headers[] = 'Timezone: 7';
        $headers[] = 'Traceid: 52003d3f-6c54-44ec-832e-9471c4c67240';
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $resultSaldoSekarang = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        header('content-type: application/json');

        $resultSaldoSekarang = json_decode($resultSaldoSekarang);


        // untuk cek hasil tradingan terakhir       

        $file_watch_js = file_get_contents("watch.js");
        $file_bot_trading = file_get_contents((__DIR__ . '/BotTradingController.php'));

        $command1 = "ps -ef | grep 'java' | grep -v grep | awk '{print $2}' | xargs -r kill -9";
        $command2 = "ps -ef | grep 'geckodriver' | grep -v grep | awk '{print $2}' | xargs -r kill -9";
        $command3 = "ps -ef | grep 'firefox' | grep -v grep | awk '{print $2}' | xargs -r kill -9";

        $saldo_sekarang = number_format($result->data->contractFullMarginAsset->currencyAmount, 2, '.', ',');
        $margin_lama = number_format($resultSaldoSekarang->data->orders[0]->margin, 2, '.', ',');
        ;
        $margin_baru = number_format($saldo_sekarang * 0.1, 2, '.', ',');

        $file_watch_js = str_replace($margin_lama, $margin_baru, $file_watch_js);
        $file_bot_trading = str_replace($margin_lama, $margin_baru, $file_bot_trading);
        file_put_contents('watch.js', $file_watch_js);
        file_put_contents((__DIR__ . '/BotTradingController.php'), $file_bot_trading);

        //
        $host = "185.211.5.241";
        $username = "root";
        $password = "mautauajakamu98";

        $ssh = new SSH2($host);
        if (!$ssh->login($username, $password)) {
            exec("curl 'https://bikinaplikasi.dev/bot-trading/call-telegram-message?telegram_id=ramdanriawan&message=login ssh untuk ganti token gagal'");
        } else {

            $ssh->exec($command1);
            $ssh->exec($command2);
            $ssh->exec($command3);
        }

        die("oke");
    }

    public function checkSaldo()
    {
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api-app.qq-os.com/api/v1/assets/0');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Authority: api-app.qq-os.com';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Encoding: *';
        $headers[] = 'Accept-Language: en-US,en;q=0.9';
        $headers[] = 'App_version: 4.33.1';
        $headers[] = 'Appid: 30004';
        $headers[] = 'Authorization: Bearer ' . $this->token;
        $headers[] = 'Channel: official';
        $headers[] = 'Cookie: __cfruid=8dfdc83610483b6c48eac7a18c71c3775f9d1a86-1657151225; __cf_bm=o3Y3JfeLfAKk5JlQbddeHC16Qa8CTR5DmNqHN4JhrSc-1657153162-0-AREzBhzDdokaOZKZCRzr/h7SvKwXplTWsycoN9K7V1MySb22BsbQcM1f7IIANoShT5PC7Nroz0KyydvefvF5BBg=';
        $headers[] = 'Device_id: e20b78f0-b177-11ec-960f-c9bb23bf51ff';
        $headers[] = 'Lang: id-ID';
        $headers[] = 'Mainappid: 10009';
        $headers[] = 'Origin: https://bingx.com';
        $headers[] = 'Platformid: 30';
        $headers[] = 'Sec-Ch-Ua: ^^.Not/A)Brand^^\";v=^^\"99^^\",';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
        $headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: cross-site';
        $headers[] = 'Sign: 967058CF0503EFB6C71E50E545D42A72F481A9D147B5C8E09128B1817B5C0792';
        $headers[] = 'Timestamp: 1657153454729';
        $headers[] = 'Timezone: 7';
        $headers[] = 'Traceid: 52003d3f-6c54-44ec-832e-9471c4c67240';
        $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        //        header('content-type: application/json');

        die(str_replace('.', ',', json_decode($result)->data->contractFullMarginAsset->currencyAmount));
    }

    public function checkJsIsActive()
    {
        $this->sendTelegramMessage2('Watch js is active!');
    }
}