apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app.kubernetes.io/name: helloweb
    app.kubernetes.io/component: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080

  externalTrafficPolicy: Local
  type: LoadBalancer
  
  selector:
    app.kubernetes.io/name: helloweb
    app.kubernetes.io/component: backend
