apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app.kubernetes.io/name: helloweb
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: helloweb
    app.kubernetes.io/component: backend
