<?php

namespace App\Admin\Controllers;

use Encore\Admin\Controllers\AuthController as BaseAuthController;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Http\Request;

class AuthController extends BaseAuthController
{
    use ThrottlesLogins;
    protected $maxAttempts = 5;
    protected $decayMinutes = 60;
    
    public function postLogin(Request $request)
    {
//        if ($this->hasTooManyLoginAttempts($request)) {
//            $this->fireLockoutEvent($request);
//            
//            return $this->sendLockoutResponse($request);
//        }
        
        $this->incrementLoginAttempts($request);
        
        return parent::postLogin($request); // TODO: Change the autogenerated stub
    }
    
    public function getLogout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();

        return redirect('/');
    }
}
